# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from oauth2_provider.settings import oauth2_settings


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0002_08_updates'),
        migrations.swappable_dependency(oauth2_settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'swappable': 'OAUTH2_PROVIDER_ORGANIZATION_MODEL',
            },
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=oauth2_settings.ORGANIZATION_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=oauth2_settings.ORGANIZATION_MODEL),
        ),
        migrations.AddField(
            model_name='grant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=oauth2_settings.ORGANIZATION_MODEL),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=oauth2_settings.ORGANIZATION_MODEL),
        ),
    ]
